### ISSUE TITLE
Frontend Todo List

### ISSUE THREAD

**Issue by jhaemin** [payasyouwant/eodiro#24]
- [ ] 무지개 색깔 css nth child로 순서대로 색깔 입히고 vue는 key index사용
- [ ] 404 페이지를 현재 url 유지하면서 보여주기
- [x] og: 메타 태그
- [ ] ★ 🏃 각 vue component에서 og:title, og:description 설정
- [x] 홈화면에서 반응하는타일의 개수를 화면크기에 맞게 최적화
- [x] AppNav가 스크롤이벤트를 무시해야할때가 필요함 → 플래그 사용
- [x] 뒤로가기 할 경우 전에 머물던 뷰 컴포넌트는 keep-alive에서 캐시 삭제 → include="[a, b, c]" 이동할때마다 캐시된 컴포넌트 이름배열 업데이트
- [x] AppNav의shadow를 box-shadow가 아닌filter: blur() 사용, 이렇게 하면 투명한공백 해결 가능. transform으로 길이조절→ transform하면똑같이 이상해짐
- [x] AppNav 첫 로드시width가 조금 더 길어지는 문제 해결
- [x] staggering 애니메이션을 js의 interval 대신 css의transition-delay로하기
- [x] 홈 화면 상자 트랜지션 시간 단축
- [ ] 받침 유무 확인해서조사 선택
- [x] AppNav의 title을watch: $route로처리
- [ ] 홈화면의 설정 버튼 하나로 뭉치기
- [x] 빌딩 색깔 예전 색깔뜨는 문제(SelectFloor.vue에서 import 잔재)
- [x] stagger효과를viewport에 들어온dom에만 적용하여퍼포먼스 향상
- [x] 느린 네트워크 환경을고려하여 건물, 층, 결과 불러오는 뷰에도스피너 추가
- [x] 시간표 시간 가운데정렬
- [x] 작은 화면에서 요일텍스트 잘림
- [x] 뱃지 숫자 있을때랑 없을 때 크기차이때문에 움직임 현상
- [x] 라이트모드 다크모드다국어
- [x] 모달 팝업햇을 때body 스크롤 막기
- [x] 층 선택화면에서 건물번호 띄우기
- [x] 시간표에서 현재 강의표시
- [x] 고객지원 이메일 표기
- [ ] 시간표 계산 최적화
- [ ] 싱글버튼이 위에 있어서 화면이 큰 디바이스에서는 조작이 어려움
- [ ] 현재 시간표로 스크롤
- [x] 더블 클릭 시 cau2/606/606이런식으로 붙으면서404로 보내버림
- [x] 대학교 리스트 검색화면에도 스피너 추가
- [x] 빈강의실 표시가 전체 강의실처럼 보일 수있음 빈 강의실/전체 강의실로 표시
- [ ] ★ alert, confirm에 대해서 자체 모달 개발
- [x] staggered animation settimeout으로 전환
- [x] 이전 애니메이션이 끝나야 다음 애니메이션이 실행되게 코드 작성하기
- [ ] ~~스피너가 화면 스크롤정도에 관계없이 항상중앙에 위치하도록 position: fixed;~~
- [ ] staggered animation이 작동할요소들의 column수에 따라 속도가 다르게 조절, column이많아질수록 속도는 빨라져야한다.
- [x] 홈에서 start box를홈 로드되고 조금 시간 차 두고 애니메이트하기
- [x] 작은 화면에서 시간표시간 폭이 좁아서 줄바꿈이 일어남
- [ ] 맨 아래로 스크롤해서가속도 스크롤 발동됐을때 싱글버튼이 나타남
- [ ] 가끔 홈화면 타일이 발동을 안함 / 가끔 홈화면 로드가 안됨
- [x] 현재 수업중인 항목의그림자가 요일을 침범함
- [ ] ★ 강의 남은 시간을 게이지바로

**Comment by jhaemin** [comment]
Moved to Trello
