### ISSUE TITLE
Backend Todo List

### ISSUE THREAD

**Issue by ihooni** [payasyouwant/eodiro#29]
- [ ] forever to pm2
- [ ] js to ts
- [ ] 주석 작업 및 code 개선
- [ ] API docs 추가
- [ ] 빈 강의실 연산 최적화
- [ ] 새로운 학교 & 학기 데이터 추가 쉽게 만들기
- [ ] 알림 API 추가 및 관리자 페이지 추가
- [ ] 서버랑 front 분리
- [ ] aws sudo su 해결

**Comment by ihooni** [comment]
Migrated to trello
